# Generated by Django 5.0.7 on 2024-07-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_video", models.FileField(upload_to="original_videos/")),
                ("extracted_audio", models.CharField(blank=True, max_length=200)),
                ("transcription", models.CharField(blank=True, max_length=200)),
                ("translated_audio", models.CharField(blank=True, max_length=200)),
                ("dubbed_video", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
