# Generated by Django 5.0.7 on 2024-07-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dubapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videofile",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
