# Generated by Django 4.2.4 on 2024-11-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dubapp', '0002_videofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='status',
        ),
    ]
